server:
  port: 8888
  servlet:
    context-path: /config

spring:
  application:
    name: service-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zvozdin/configuration-store
          default-label: master
          searchPaths: /global,/{application}
